# Generated by Django 5.1.2 on 2024-10-26 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="utility_rate_selected",
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
    ]
