# Generated by Django 5.1.2 on 2024-10-31 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="tariff_selected",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
