# Generated by Django 5.1.2 on 2024-10-31 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_project_tariff_selected"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="tariff_selected",
        ),
    ]
