# Generated by Django 5.1.2 on 2024-10-31 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_remove_project_tariff_selected"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="more_likely_tariff",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="utility_rate",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
